name: Dependency review
on:
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate   # low|moderate|high|critical
          # allow-licenses: Apache-2.0,MIT  # optional guardrail
