name: Dependency Submission (Maven)
on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }
permissions:
  contents: read
jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: 'temurin', java-version: '17' }
      - name: Build (no tests) so deps resolve
        run: mvn -q -DskipTests package
      - name: Submit Maven dependencies
        uses: advanced-security/maven-dependency-submission-action@v4
