name: Dependency Submission (Maven)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: write   # <— needed for dependency submission
jobs:
  submit:
    # Skip untrusted forks (they only get a read-only token)
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - name: Build to resolve deps (optional but helpful)
        run: mvn -q -DskipTests package
      - name: Submit Maven dependencies
        uses: advanced-security/maven-dependency-submission-action@v4
