# .github/workflows/sbom.yml
name: Build + SBOMs
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      # 1) Build JAR so bytes exist to hash
      - name: Build (package)
        run: mvn -B -DskipTests clean package

      # 2) CycloneDX SBOM (hashes are embedded in components[].hashes)
      #    If your POM already binds makeBom at 'package', this step is optional.
      - name: Generate CycloneDX SBOM
        run: mvn -B org.cyclonedx:cyclonedx-maven-plugin:makeBom

      # 3) SPDX with file checksums (filesystem scan)
      - name: Generate SPDX (Syft)
        uses: anchore/sbom-action@v0
        with:
          path: target/
          format: spdx-json
          output-file: target/syft.spdx.json

      # 4) Hash the SBOM files themselves (sidecar .sha256)
      - name: Create SHA-256 for SBOM files
        shell: bash
        run: |
          set -euo pipefail
          for f in target/bom.xml target/bom.json target/syft.spdx.json; do
            if [ -f "$f" ]; then
              sha256sum "$f" > "$f.sha256"
            fi
          done

      # 5) (Optional) Export GitHub's manifest-based SPDX
      - name: Export SPDX from GitHub Dependency Graph
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api -H "Accept: application/vnd.github+json" \
            "/repos/${{ github.repository }}/dependency-graph/sbom?ref=${{ github.sha }}" \
            --jq '.sbom' > target/gh-depgraph.spdx.json

      - name: Upload SBOM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sboms
          path: |
            target/bom.xml
            target/bom.json
            target/bom.xml.sha256
            target/bom.json.sha256
            target/syft.spdx.json
            target/syft.spdx.json.sha256
            target/gh-depgraph.spdx.json
